name: pre-commit

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@latest
      - uses: actions/setup-python@latest
      - uses: actions/setup-go@latest
        with:
          go-version: "^1.18"
      - run: |
          go install github.com/aquasecurity/tfsec/cmd/tfsec@latest
          go install github.com/terraform-docs/terraform-docs@latest
          go install golang.org/x/lint/golint@latest
          go install golang.org/x/tools/cmd/goimports@latest
          go install github.com/fzipp/gocyclo/cmd/gocyclo@latest
      - uses: pre-commit/action@latest
